name: Build C++ with CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: cmake .. 
        working-directory: ./build

      - name: Build project
        run: make
        working-directory: ./build

      - name: Upload output binary
        uses: actions/upload-artifact@v4
        with:
          name: my_cpp_binary
          path: build/**
