name: Build C++ Project with CMake & Submodules

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: cmake ..
        working-directory: ./build

      - name: Build project
        run: make
        working-directory: ./build

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: cpp-output
          path: build/**
